harnessApiVersion: '1.0'
type: PROMETHEUS
prometheusUrl: http://54.219.179.240:30000/
usageRestrictions:
  appEnvRestrictions:
  - appFilter:
      filterType: ALL
    envFilter:
      filterTypes:
      - PROD
  - appFilter:
      filterType: ALL
    envFilter:
      filterTypes:
      - NON_PROD
