harnessApiVersion: '1.0'
type: APPLICATION_MANIFEST
helmChartConfig:
  chartName: nginx-ingress
  connectorName: nginx-ingress-controller
helmCommandFlag:
  valueMap:
    TEMPLATE: --debug
storeType: HelmChartRepo
